"""Phase C: normalize + filter cached GATE quizzes into ingest-ready items.

Reads the raw JSON cached by `scrape_gfg`, keeps only questions this app can
represent, and emits text blocks (question + 4 options + answer KEY only) that
the existing `ingest_exemplars` pipeline parses, classifies, verifies and
inserts. GfG's explanation prose is intentionally discarded — explanations and
distractor rationales are regenerated by the authoring LLM (copyright-clean).

Keep a question only if ALL hold:
  - exactly 4 options and exactly one marked `correct` (drops NAT and MSQ);
  - no image/table/svg in the question or any option (text + LaTeX model only).

Out-of-scope subjects (aptitude, maths, digital logic, compiler design) are NOT
filtered here — they carry no per-question subject tag. The LLM parser maps them
to courseSlug "none" and `ingest` drops them. See GATE_INGEST.md.

Usage:
    python -m app.ingest.gfg_normalize          # normalize all cached papers
"""
from __future__ import annotations

import html
import json
import re
from collections import Counter
from pathlib import Path

from app.ingest.scrape_gfg import PAPERS, RAW_DIR

OUT_DIR = Path(__file__).resolve().parents[2] / "data" / "gate_ingest"
LETTERS = ["A", "B", "C", "D"]
_MEDIA_RE = re.compile(r"<(img|table|svg|iframe|picture)\b|data:image", re.IGNORECASE)
_TAG_RE = re.compile(r"<[^>]+>")


def has_media(html_str: str) -> bool:
    return bool(_MEDIA_RE.search(html_str or ""))


def html_to_text(s: str) -> str:
    """Strip HTML to readable plaintext, preserving sup/sub as ^()/_()."""
    if not s:
        return ""
    s = re.sub(r"<sup\b[^>]*>(.*?)</sup>", r"^(\1)", s, flags=re.IGNORECASE | re.DOTALL)
    s = re.sub(r"<sub\b[^>]*>(.*?)</sub>", r"_(\1)", s, flags=re.IGNORECASE | re.DOTALL)
    s = re.sub(r"</(p|div|li|br|tr)\s*>", "\n", s, flags=re.IGNORECASE)
    s = re.sub(r"<br\s*/?>", "\n", s, flags=re.IGNORECASE)
    s = _TAG_RE.sub("", s)
    s = html.unescape(s)
    s = re.sub(r"[ \t ]+", " ", s)
    s = re.sub(r"\n\s*\n+", "\n", s)
    return s.strip()


def normalize_quiz(results: list[dict], exam: str, year: int) -> tuple[list[str], Counter]:
    """Return (kept text blocks, drop-reason counter) for one paper."""
    kept: list[str] = []
    drops: Counter = Counter()

    for q in results:
        answers = q.get("answers", [])
        n_correct = sum(1 for a in answers if a.get("correct"))
        if len(answers) != 4:
            drops["not-4-options (NAT)"] += 1
            continue
        if n_correct != 1:
            drops["not-single-correct (MSQ)"] += 1
            continue
        if has_media(q.get("question", "")) or any(has_media(a.get("answer", "")) for a in answers):
            drops["image/table"] += 1
            continue

        qtext = html_to_text(q.get("question", ""))
        opts = [html_to_text(a.get("answer", "")) for a in answers]
        if not qtext or any(not o for o in opts):
            drops["empty-after-strip"] += 1
            continue
        correct_letter = LETTERS[next(i for i, a in enumerate(answers) if a.get("correct"))]

        lines = [
            f"{exam} ({year}) — past-year MCQ.",
            "",
            f"Question: {qtext}",
            "",
            "Options:",
            *(f"{LETTERS[i]}. {opts[i]}" for i in range(4)),
            "",
            f"Correct answer: {correct_letter}",
        ]
        kept.append("\n".join(lines))

    return kept, drops


def normalize_all() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    total_kept = 0
    total_seen = 0
    for slug, year in PAPERS.items():
        raw = RAW_DIR / f"{slug}.json"
        if not raw.exists():
            print(f"  missing raw cache for {slug} (run scrape_gfg first)")
            continue
        results = json.loads(raw.read_text())
        exam = "GATE CS " + str(year) if "set" not in slug else "GATE CS"
        kept, drops = normalize_quiz(results, exam=f"GATE CS {year}", year=year)
        items = [{"text": t, "source": slug} for t in kept]
        (OUT_DIR / f"{slug}.json").write_text(json.dumps(items, ensure_ascii=False, indent=2))
        total_kept += len(kept)
        total_seen += len(results)
        drop_str = ", ".join(f"{k}={v}" for k, v in sorted(drops.items()))
        print(f"  {slug:24} kept {len(kept):2}/{len(results)}  ({drop_str})")
    print(f"\nNormalized {total_kept} candidate MCQs (from {total_seen} raw) -> {OUT_DIR}")
    print("Subject filtering (out-of-scope -> courseSlug 'none') happens during ingest.")


if __name__ == "__main__":
    normalize_all()
