"""Phase B: fetch GATE CS previous-year quizzes from GeeksforGeeks.

The public quiz pages are backed by a JSON API:

    GET https://apiwrite.geeksforgeeks.org/quiz/gfg/<slug>/?page=N&page_size=M
    -> { count, next, previous, results: [ {
           id, title, question(HTML), explanation(HTML),
           answers: [ { answer(HTML), correct(bool) }, ... ] } ] }

This module ONLY fetches and caches the raw JSON to disk (run-once, polite,
rate-limited). It does no filtering or transformation — see `gfg_normalize`.

We deliberately do NOT reuse the cached explanation prose downstream (it is
GfG's copyrighted text); only the question + options + answer key are used, and
explanations are regenerated by the authoring LLM. The underlying GATE questions
are official public IIT exam papers. Scrape once, cache, be polite.

Usage:
    python -m app.ingest.scrape_gfg            # fetch all (skip already-cached)
    python -m app.ingest.scrape_gfg --force    # re-fetch even if cached
"""
from __future__ import annotations

import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API = "https://apiwrite.geeksforgeeks.org/quiz/gfg/{slug}/?page={page}&page_size={size}"
PAGE_SIZE = 100
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
)
DELAY_SECONDS = 1.5  # be polite between requests
RAW_DIR = Path(__file__).resolve().parents[2] / "data" / "gate_raw"

# slug -> exam year (used downstream for examName/year metadata).
PAPERS: dict[str, int] = {
    "gate-cs-2025-set-1": 2025,
    "gate-cs-2025-set-2": 2025,
    "gate-cse-2024-2": 2024,
    "gate-cse-2024-set-2": 2024,
    "gate-cse-2023-6": 2023,
    "gate-cs-2022-23": 2022,
    "gate-cs-2021-set-1-2": 2021,
    "gate-cs-2021-set-2-2": 2021,
    "gate-cs-2020": 2020,
    "gate-cs-2019": 2019,
    "gate-cs-2018": 2018,
}


def _get_json(url: str, *, retries: int = 3) -> dict:
    last_err: Exception | None = None
    for attempt in range(retries):
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        try:
            with urllib.request.urlopen(req, timeout=40) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
            last_err = e
            time.sleep(DELAY_SECONDS * (attempt + 1))
    raise RuntimeError(f"failed to fetch {url}: {last_err}")


def fetch_quiz(slug: str) -> list[dict]:
    """Follow pagination and return all `results` for one quiz slug."""
    results: list[dict] = []
    page = 1
    while True:
        data = _get_json(API.format(slug=slug, page=page, size=PAGE_SIZE))
        batch = data.get("results", [])
        results.extend(batch)
        if not data.get("next") or not batch:
            break
        page += 1
        time.sleep(DELAY_SECONDS)
    return results


def scrape_all(*, force: bool = False) -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    for slug in PAPERS:
        out = RAW_DIR / f"{slug}.json"
        if out.exists() and not force:
            n = len(json.loads(out.read_text()))
            print(f"  cached  {slug}  ({n} questions)")
            continue
        try:
            results = fetch_quiz(slug)
        except Exception as e:  # keep going across papers
            print(f"  FAILED  {slug}: {e}")
            continue
        out.write_text(json.dumps(results, ensure_ascii=False, indent=2))
        print(f"  fetched {slug}  ({len(results)} questions) -> {out.name}")
        time.sleep(DELAY_SECONDS)


if __name__ == "__main__":
    scrape_all(force="--force" in sys.argv[1:])
    print(f"\nRaw quizzes cached under {RAW_DIR}")
